-- Q1. all rows and columns from customer
select * from customer;

-- Q2. List all customers who purchased items in the Winter season
select customer_id, item_purchased, season
from customer
where season = 'Winter';

-- Q3. Find the average purchase amount of all customers.
select avg(purchase_amount) as avg_purchase
from customer;

-- Q4. Show the number of customers by gender.
select gender, count(*) as total_customers
from customer
group by gender;

-- Q5. Retrieve customers who gave a review rating above 4.0.
SELECT customer_id, item_purchased, review_rating
FROM customer
WHERE review_rating > 4.0;

-- Q6. Find the maximum and minimum purchase amounts.

select max(purchase_amount) as max_purchase,
       min(purchase_amount) as min_purchase
from customer

-- Q7. Calculate the total revenue generated by each category.

SELECT category, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY category
ORDER BY total_revenue DESC;

-- Q8. Identify the top 5 customers with the highest number of previous purchases.

SELECT customer_id, previous_purchases
FROM customer
ORDER BY previous_purchases DESC
LIMIT 5;

-- Q9. Find the average purchase frequency days by age group.

SELECT age_group, AVG(purchase_frequency_days) AS avg_frequency
FROM customer
GROUP BY age_group
ORDER BY avg_frequency ASC;

-- Q10. Get the most popular payment method among customers with active subscriptions.

SELECT payment_method, COUNT(*) AS usage_count
FROM customer
WHERE subscription_status = 'Yes'
GROUP BY payment_method
ORDER BY usage_count DESC;

-- Q11. Rank items within each category by total purchase amount (using window functions).

SELECT category, item_purchased, SUM(purchase_amount) AS total_sales,
       RANK() OVER (PARTITION BY category ORDER BY SUM(purchase_amount) DESC) AS rank_in_category
FROM customer
GROUP BY category, item_purchased;
